apiVersion: apps/v1
kind: Deployment
metadata:
  name: r2sometools
  labels:
    app: r2sometool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: r2sometool
  template:
    metadata:
      labels:
        app: r2sometool
    spec:
      containers:
      #- name: nginx
      #  image: nginx:1.14.2
      #  ports:
      #  - containerPort: 80
      - name: r2sometoolcontainer
        #image: gcr.io/google_containers/busybox
        #image: gcr.io/google-containers/echoserver:1.10
        #image: ghcr.io/mendhak/http-https-echo:30
        #image: oliverisaac/alpine-nettools
        #image: raesene/alpine-nettools
        image: curlimages/curl:latest
        #image: centos:7    #3YOLD
        #image: alpine
        #image: ubuntu:noble
        #image: fedora:latest
        imagePullPolicy: IfNotPresent
        command: [ "sleep" , "3600"  ]
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
      restartPolicy: Always
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
